import {StyleSheet, Dimensions, Platform} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  header: {
    width: width,
    height: 100,
    backgroundColor: 'white',
  },
  headerUpperArea: {
    display: 'flex',
    width: '92%',
    marginTop: Platform.OS == 'ios' ? 10 : 45,
    flexDirection: 'row',
    marginLeft: 'auto',
  },
  hr: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  mainBodyPartOne: {
    width: width,
    height: '100%',
    backgroundColor: 'white',
    position: 'relative',
    zIndex: 0,
    flex:1,
    marginTop:0,
  },
  partOneButtons: {
    marginLeft: 'auto',
    marginRight: 'auto',
    // height: '30%',
    width: '90%',
    backgroundColor: '#D6E1E3',
    borderRadius: 4,
    flexDirection: 'row',
    // marginTop: 30,
    paddingVertical:2,
    justifyContent: 'center',
    marginBottom: 10,
  },
  partOneButton: {
    fontSize: 13,
    textAlign: 'center',
    width: '50%',
    borderRadius: 4,
    color: '#343434',
    padding: 8,
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  JoinLeft: {
    position: 'relative',
    left: 13,
  },
  JoinRight: {
    position: 'relative',
    right: 13,
  },
  checkrateButtonContainer: {
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  checkrateButton: {
    alignItems: 'center',
    backgroundColor: '#1CC88A',
    padding: 15,
    borderRadius: 4,
  },

  mainBodyPartTwo: {
    width: width,
    height: height - 300,
    backgroundColor: '#ffffff',
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
    position: 'absolute',
    top: '40%',
    alignItems: 'center',
    zIndex: 1,
  },
  giftCardBodyPatOne: {
    width: width,
    height: height,
    backgroundColor: '#f2f2f2',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    position: 'absolute',
    top: '9%',
    // alignItems:"center",
  },
  giftCardsBodyPartTwo: {
    width: width,
    height: height - 450,
    backgroundColor: '#ffffff',
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
    position: 'absolute',
    top: '70%',
    alignItems: 'center',
    zIndex: 1,
  },
  emptyCont: {
    height: 'auto',
    width:'100%',
    backgroundColor:'#fff',
    borderRadius:8,
    marginVertical:3,
    paddingHorizontal:9,
    paddingVertical:10,
    elevation:0,
},
  cont: {
    width:'100%',
    paddingVertical:1,
    paddingHorizontal:7,
    flex:1,
  },
});
export default styles;
