import { StyleSheet, Dimensions, Platform } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
const { width, height } = Dimensions.get('screen');
const styles = StyleSheet.create({
  header: {
    width: width,
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: Platform.OS == 'ios' ? 0 : 10,
  },
  headerHeading: {
    textAlign: 'center',
    fontSize: 16,
    marginLeft: -18,
    marginTop: 14,
    color: '#343434',
  },
  hr: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: '#f1f1f1',
  },
  mainBodyPartOne: {
    width: width,
    height: '100%',
    backgroundColor: '#f3f5f9',
    position: 'relative',
    zIndex: 0,
    flex:1,
    paddingTop:5,
  },
  partOneButtons: {
    marginLeft: 'auto',
    marginRight: 'auto',
    // height: '30%',
    width: '90%',
    backgroundColor: '#D6E1E3',
    borderRadius: 4,
    flexDirection: 'row',
    // marginTop: 30,
    paddingVertical:2,
    justifyContent: 'center',
    marginBottom: 10,
  },
  partOneButton: {
    fontSize: 13,
    textAlign: 'center',
    width: '50%',
    borderRadius: 4,
    color: '#343434',
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  JoinLeft: {
    position: 'relative',
    left: 2,
  },
  JoinRight: {
    position: 'relative',
    right: 2,
  },
  checkrateButtonContainer: {
    borderRadius: 4,
    // marginLeft:28,
    alignSelf: 'center',
    height: 45,
    width: '100%',
    marginHorizontal: 20,
  },
  checkrateButton: {
    alignItems: 'center',
    backgroundColor: '#1CC88A',
    paddingVertical: 8,
    marginTop: 10,
    borderRadius: 10,
  },

  mainBodyPartTwo: {
    width: width,
    height: RFValue(100),
    backgroundColor: '#1CC88A',
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
    zIndex: 1,
  },
  giftCardBodyPatOne: {
    flex: 1,
    width: width,
    height: height,
    backgroundColor: '#fff',

    // alignItems:"center",
  },
  giftCardsBodyPartTwo: {
    width: width,
    height: RFValue(100),
    backgroundColor: '#1CC88A',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
  },
  text: {
    alignSelf: 'center', marginBottom: 20,
    backgroundColor:'#fff',
    paddingLeft: 15, borderRadius: 5,
    width: '100%', borderWidth: StyleSheet.hairlineWidth, borderColor: '#ddd',
    fontSize: 13, marginRight: 0,
    height:45,
    fontFamily: 'Nunito-Regular',
  },
  drop: {
    backgroundColor: 'transparent',
    height: 'auto',
    width: '100%', paddingHorizontal: 0,
    paddingVertical: 0,
    alignSelf: 'center',
  },
  drop2: {
    backgroundColor: '#fff',
    height: 56,
    width: '100%', paddingHorizontal: 20,
    paddingVertical: 10,
    alignSelf: 'center',
  },
  bottomContainerForIos: {
    height: 30,
    width: '100%',
    backgroundColor: 'transparent',
  },
  dropDown: {
    backgroundColor:'#fff',
    height: 'auto',
    width: '100%',
    paddingHorizontal:0,
    marginBottom:15,
    paddingVertical: 0,
    borderRadius:5,
    borderColor:'#ddd',
    borderWidth:StyleSheet.hairlineWidth,
    alignSelf: 'center',
  },
  dropDownBtn: {
width:'100%',
height:45,backgroundColor:'transparent',
  },
  rowStyle: {
    backgroundColor: '#f9f9f9', borderBottomWidth:StyleSheet.hairlineWidth, borderBottomColor:'#ddd', width: '100%'
  },
  btnText: {
    textAlign: 'left',
    fontSize: 13,
    color: '#343434',
    fontFamily: 'Nunito-Regular',
  },
  submitBtn: {
    alignSelf: 'center',
    backgroundColor: '#1CC88A',
    width: '100%',
    borderRadius: 4,
    marginBottom: 10,
    padding: 10,
  },
});
export default styles;
