import { ActionTypes } from '../constants';

export interface HomeScreen {
  toprates: TopRate[];
  wallet:   Wallet;
}

export interface TopRate {
  cardName:  string;
  cardValue: number;
  cardRate:  number;
}

export interface Wallet {
  cashBalance:    number;
  airtimeBalance: number;
}

const initialState : HomeScreen = {
  toprates: [],
  wallet: {cashBalance:0, airtimeBalance:0}
}

function homeReducer(state = initialState, { type, payload }) {
  switch (type) {
    case ActionTypes.HOME_DATA:
      console.log("HOME_DATA",payload );
      
      return { ...payload };
    
    default:
     return state;
  }
}
export default homeReducer;
// Generated by https://quicktype.io

