export const ActionTypes = {

  
  GET_SETTING: 'GET_SETTING',
  GET_NOTIFICATION : 'GET_NOTIFICATION',
  GETCODES : 'GETCODES',
  GET_TRADECOUNTER : 'GET_TRADECOUNTER',
  UPDATE_TRADEDATA : 'UPDATE_TRADEDATA',
  
  UPDATE_TRADEDATASTATUS : 'UPDATE_TRADEDATASTATUS',

  //// ------ USER ------ ////

  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  HOME_DATA: 'HOME_DATA',
  GET_CARDS: 'GET_CARDS',


  ADD_CARD: 'ADD_CARD',
  GET_CARD: 'GET_CARD',
  UPDATE_CARD: 'UPDATE_CARD',
  UPDATE_DISABLESTATUS: 'UPDATE_DISABLESTATUS',
  GET_CARDSID: 'GET_CARDSID',
  ADDCODES: 'ADDCODES',
  DELETE_GIFTCARDS: 'DELETE_GIFTCARDS',
  DELETE_ADMINCARD: 'DELETE_ADMINCARD',



  GET_USER_DETAILS: 'GET_USER_DETAILS',
  GET_BANK_DETAILS: 'GET_BANK_DETAILS',
  UPDATE_BANK_DETAILS: 'UPDATE_BANK_DETAILS',
  GET_WALLET_AMOUNT: 'GET_WALLET_AMOUNT',
  GET_BONUS_LIST: 'GET_BONUS_LIST',
  EDIT_USER_DETAILS: 'EDIT_USER_DETAILS',
  GET_NEWS: 'GET_NEWS',
  ADD_GIFTCARD: 'ADD_GIFTCARD',
  GET_GIFTCARD: 'GET_GIFTCARD',
  CREATE_TRADE: 'CREATE_TRADE',
  GET_TRADE : 'GET_TRADE',
  GET_TRADE_ID : 'GET_TRADE_ID',
  GET_RATEID :'GET_RATEID',
  GET_USER_BY_ID : 'GET_USER_BY_ID',

  UPDATE_USER_STATS : 'UPDATE_USER_STATS',
  GET_USER_STATS : 'GET_USER_STATS', 

  UPDATE_ONRETRY : 'UPDATE_ONRETRY',
  UPDATE_ONSWITCH : 'UPDATE_ONSWITCH',
  GET_TRANSCOUNT : 'GET_TRANSCOUNT', 
  EDIT_USER_ROLE: 'EDIT_USER_ROLE',
  GET_STATUS : 'GET_STATUS',
  SUPPORT_GUEST : 'SUPPORT_GUEST',


  GET_TRANSACTIONUSER : 'GET_TRANSACTIONUSER',

  GET_WITHDRAWAL_BY_ID : 'GET_WITHDRAWAL_BY_ID',
  CREATEWITH_DRAW : 'CREATEWITH_DRAW',
  GET_WITHDRAW : 'GET_WITHDRAW',
  GET_GIFTCARDBYID : 'GET_GIFTCARDBYID',
  UPDATE_BONUS_STATUS : 'UPDATE_BONUS_STATUS',
  UPDATE_RATE_STATUS : 'UPDATE_RATE_STATUS',
  CHANGE_PASS : 'CHANGE_PASS',
  REMOVE_FCM_TOKEN : 'REMOVE_FCM_TOKEN',
  SET_FCM_TOKEN : 'SET_FCM_TOKEN',
  AIR_TIME_DATA_PAYMENTS : 'AIR_TIME_DATA_PAYMENTS',

  BANK_NAMES : 'BANK_NAMES',
  GET_BILLERS : 'GET_BILLERS',
  GET_CABLE_BILLERS : 'GET_CABLE_BILLERS',
  DSTV_GOTV_PAYMENTS : 'DSTV_GOTV_PAYMENTS',
  GET_OUR_RATE : 'GET_OUR_RATE',
  GET_TOPRATE : 'GET_TOPRATE',
  RESOLVE_ACC : 'RESOLVE_ACC',
  RESET_PASS : 'RESET_PASS',
  VERIFY_CODE : 'VERIFY_CODE',
  SET_NEWPASS : 'SET_NEWPASS',
  ONGOING__COUNT : 'ONGOING__COUNT',
  COMPLETED__COUNT : 'COMPLETED__COUNT',
  GET_PENDING_WITHDRAWAL_COUNT_USER : 'GET_PENDING_WITHDRAWAL_COUNT_USER',
  GET_DECLINED_WITHDRAWAL_COUNT_USER  : 'GET_PENDING_WITHDRAWAL_COUNT_USER',
  
  


};
