import {StyleSheet, Dimensions, StatusBar, Platform} from 'react-native';
const {width, height} = Dimensions.get('screen');
import {RFValue} from 'react-native-responsive-fontsize';

const styles = StyleSheet.create({
  header: {
    width: width,
    paddingTop: Platform.OS == 'ios' ? 0 : 0,
    paddingBottom: 15,
    height:60,
    backgroundColor:'#fff'
  },
  headerUpperArea: {
    display: 'flex',
    width: '70%',
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  modalheader: {
      width: width,
      height: 60,
      alignItems: 'center',
      backgroundColor: '#fff-',
      flexDirection: 'row',
      justifyContent: 'space-between',
  },

  balanceInfoContainer: {
    width: width,
    marginTop: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: Platform.OS == 'ios' ? 10 : 0,
  },
  balanceContainer: {
    width: 141,
    height: 157,
    backgroundColor: '#343434',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
  },
  currencySignContainer: {
    width: 50,
    height: 50,
    backgroundColor: '#CD2626',
    borderRadius: 100,
    marginLeft: 15,
    marginTop: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  withdrawlInfo: {
    width: 150,
    marginTop: 5,
  },
  circileAndTextRow: {
    display: 'flex',
    flexDirection: 'row',
  },
  circleIcon: {
    marginRight: 10,
    marginTop: 3,
    width: 10,
    height: 10,
  },
  verticalLine: {
    height: 32,
    width: 1,
    backgroundColor: '#F2F2F2',
    position: 'relative',
    right: 15,
    top: 15,
  },
  floatValueContainer: {
    height: 80,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
    borderRadius: 15,
    marginVertical: 5,
    display: 'flex',
    backgroundColor:'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  borderLine: {
    marginTop: 20,
    paddingTop: 5,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: '#F2F2F2',
  },
  bankAccountInfoContainer: {
  
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent:'space-between',
    marginVertical:4,
  },
  editIconContainer: {
    width: 'auto',
    justifyContent: 'center',
    flexDirection:'row',
    height: 30,
    borderRadius: 5,
    backgroundColor: 'white',
    shadowColor: '#000',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#f2f2f2',
    marginBottom:10,
    alignItems: 'center',
    paddingHorizontal:10,
  },
  NewTextInputStyle: {
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#F1F1F1',
    width: '100%',
    borderRadius:8,
    height: 46,
    paddingLeft:10,
    color: '#343434',
    fontFamily: 'Nunito-Regular',
    fontSize: 13,
    marginTop: 10,
  },
  GreenButton: {
    height: 53,
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    fontWeight: '600',
    alignContent: 'center',
    justifyContent: 'center',
    textAlignVertical: 'center',
    color: '#fff',
    backgroundColor: '#1CC88A',
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: RFValue(16.5),
    width: '100%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 50},
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 2,
  },
  headerHeading: {
    color: 'white',
    textAlign: 'center',
    marginTop: '15%',
    fontSize: 25,
    backgroundColor: '#435c5f',
    paddingVertical: '6%',
    paddingHorizontal: '8%',
    borderRadius: 100,
  },
  headerText: {
    color: 'white',
    textAlign: 'center',
  },
  headerHeadingContainer: {
    width: '90%',
    marginBottom: 10,
    position: 'absolute',
    left: '5.3%',
    top: height > 570 ? '24%' : '20%',
    zIndex: 2,
  },

  headerHeading2: {
    alignSelf: 'center',
    color: '#343434',
    width: '80%',
    backgroundColor: 'transparent',
    fontSize: 30,
    textAlign: 'center',
    borderColor: '#F1F1F1',
    fontFamily: 'Nunito-Regular',
  },
  mainBody: {
    width: width,
     height: height,
    backgroundColor: '#f8fafa',
  },
  viewItems: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignSelf: 'center',
  },
  smBlueText: {
    fontSize: 10,
    color: 'blue',
  },
  arrowIcon: {
    width: 12,
    height: 10,
    marginLeft: 5,
    marginTop: 2,
  },

  mainBodyCards: {
    width: '107%',
    borderWidth: 0.5,
    borderColor: '#F1F1F1',
    marginTop: 50,
    backgroundColor: 'white',
    paddingHorizontal: 25,
    marginLeft: -10,
    height: '30%',
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
  },
  mainBodyCardContent1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 7,
    marginBottom: 10,
  },
  iconStyle: {
    width: 10,
    height: 20,
  },
  mainBodyCardContent: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    marginHorizontal: 10,
    borderBottomWidth: 1,
    paddingVertical: 15,
    borderColor: 'rgba(0,0,0,0.2)',
  },
  changePasswordButton: {
    color: 'black',
    width: '108%',
    marginLeft: -12,
    backgroundColor: 'white',
    fontSize: 13,
    borderRadius: 3,
    textAlign: 'center',
    marginTop: 10,
    borderWidth: 0.5,
    borderColor: '#F1F1F1',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
  },
  changePasswordButton1: {
    color: 'black',
    width: '108%',
    marginLeft: -12,
    backgroundColor: 'white',
    fontSize: 12,
    borderRadius: 3,
    paddingLeft: 15,
    textAlign: 'center',
    marginTop: 10,
    borderWidth: 0.5,
    borderColor: '#F1F1F1',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
    fontFamily: 'Nunito-Regular',
  },
  bodyBottom: {
    marginTop: 10,
    // width: width,
    // height: "42%",
    // marginLeft: -32,
    // paddingHorizontal: 8,
    marginBottom: 20,
  },
  lowerCard: {
    width: '90%',
    // height:"60%",
    marginTop: 20,
    backgroundColor: 'white',

    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 50},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 5,

    padding: 10,
  },
  upperCardPortion: {
    justifyContent: 'space-between',
  },
  hr: {
    borderTopWidth: 1.5,
    borderColor: '#F1F1F1',
    marginTop: 10,
    marginBottom: 8,
  },
  lowerPortion: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  smFontSize: {
    fontSize: 11,
    marginBottom: 2,
  },
  mdFontBlackColor: {
    color: 'black',
  },
  header_FontSize: {
    fontSize: 18,
  },
  
  hr2: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: '#f1f1f1',
  },
  mainBodyPartOne: {
    width: width,
    height: '100%',
    backgroundColor: 'white',
    position: 'relative',
    zIndex: 0,
    flex:1,
    marginTop:10,
  },
  partOneButtons: {
    marginLeft: 'auto',
    marginRight: 'auto',
    // height: '30%',
    width: '90%',
    backgroundColor: '#D6E1E3',
    borderRadius: 4,
    flexDirection: 'row',
    // marginTop: 30,
    paddingVertical:2,
    justifyContent: 'center',
    marginBottom: 10,
  },
  partOneButton: {
    fontSize: 13,
    textAlign: 'center',
    width: '50%',
    borderRadius: 4,
    color: '#343434',
    padding: 5,
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  JoinLeft: {
    position: 'relative',
    left: 2,
  },
  JoinRight: {
    position: 'relative',
    right: 2,
  },
  submitBtn: {
    alignSelf: 'center',
    backgroundColor: '#1CC88A',
    width: 100,
    borderRadius: 8,
    marginBottom: 10,
    padding: 8,
  },
  loader: {
    backgroundColor:'#f3f5f9', height:30, justifyContent:'center', alignItems:'center',width:30,padding:10,borderRadius:5, elevation:2,
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0.5,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center'
  }
});

export default styles;
